// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.sbs;

public interface currentTemperatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.currentTemperature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();
}
