// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package grpc.sbs;

public interface FloorsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lighting.FloorsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 floorNo = 1;</code>
   */
  int getFloorNo();
}
