// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Occupancy.proto

package grpc.sbs;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingSystem.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
