// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupancy.proto

package grpc.sbs;

public interface OccupancyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *if time allows plan to change to time of request instead of name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *if time allows plan to change to time of request instead of name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
