// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lighting.proto

package grpc.sbs;

public final class SBSLighServiceImpl {
  private SBSLighServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_FloorsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_FloorsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lighting_CompletedActionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lighting_CompletedActionsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016lighting.proto\022\010lighting\" \n\rFloorsRequ" +
      "est\022\017\n\007floorNo\030\001 \001(\005\"+\n\030CompletedActions" +
      "Response\022\017\n\007message\030\001 \001(\t2a\n\017LightingSer" +
      "vice\022N\n\013lightSwitch\022\027.lighting.FloorsReq" +
      "uest\032\".lighting.CompletedActionsResponse" +
      "\"\000(\001B \n\010grpc.sbsB\022SBSLighServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lighting_FloorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lighting_FloorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_FloorsRequest_descriptor,
        new java.lang.String[] { "FloorNo", });
    internal_static_lighting_CompletedActionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lighting_CompletedActionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lighting_CompletedActionsResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
