// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupancy.proto

package grpc.sbs;

public final class SBSOccupServiceImpl {
  private SBSOccupServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_OccupancyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_OccupancyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupancy_OccupancyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupancy_OccupancyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017occupancy.proto\022\toccupancy\" \n\020Occupanc" +
      "yRequest\022\014\n\004name\030\001 \001(\t\"$\n\021OccupancyRespo" +
      "nse\022\017\n\007message\030\001 \001(\t2Z\n\016CounterService\022H" +
      "\n\toccupancy\022\033.occupancy.OccupancyRequest" +
      "\032\034.occupancy.OccupancyResponse\"\000B!\n\010grpc" +
      ".sbsB\023SBSOccupServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_occupancy_OccupancyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_occupancy_OccupancyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_OccupancyRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_occupancy_OccupancyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_occupancy_OccupancyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupancy_OccupancyResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
