// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.sbs;

public interface tempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.tempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
